version: '1'
author: CodIsAFish
language: C#
dockerfile: ".docker/Dockerfile"
code: "/code"
workdir: "/code/%day%"
runonce: dotnet publish -o publish_dir -c Release
cmd: publish_dir/Day%day%
daypath: "%day%"